---
common_apt_packages:
  - virtualenvwrapper
  - tmux
  - tree
  - vim
  - gcc
  - libdbus-glib-1-2 # tor browser bundle
  - git #tbselenium depends
  - python-dev # psutil depends
  - libpcap-dev # pcapy depends
  - gnupg-curl
tbb_arch: 64
tbb_release: 6.0.3
tbb_locale: en-US

tbb_username: "{{ ansible_ssh_user }}"
